- name: Create an EC2 instance
  ec2:
    key_name: "{{ pem_key }}"
    region: "{{ region }}"
    group_id: "{{ demo_firewall.group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: yes
    count_tag:
      Name: ec2_vm
    exact_count: 1
    vpc_subnet_id: subnet-416f1628
    assign_public_ip: yes
  register: my_ec2

- debug:
    var: my_ec2
    
#- name: wait for the servers to appear on the network
#  wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=180 state=started
#  with_items: ec2.tagged_instances

#- name: add server ip addresses to hosts group
#  add_host: hostname={{ item.public_ip }} groupname=launched
#  with_items: ec2.tagged_instances
