---
- name: associate subnet to the VPC
  ec2_vpc_subnet:
   state: present
   vpc_id: "{{ my_vpc.vpc.id }}"
   region: "{{ region }}"
   cidr: "{{ subnet_cidr }}"
   map_public: yes
   resource_tags:
     Name: "{{ subnet_name }}"
  register: my_subnet
